### ISSUE TITLE
TypeError: Cannot call method 'text' of undefined

### ISSUE THREAD

**Issue by garyyu** [zaidka/genieacs#111]
When ACS request CPE to download file, once ACS receive a "DownloadResponse" as below:

<SOAP-ENV:Envelope
xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:cwmp="urn:dslforum-org:cwmp-1-0"><SOAP-ENV:Header><cwmp:ID
SOAP-ENV:mustUnderstand="1">55ed166ef0970db7056f68cc</cwmp:ID></SOAP-ENV:Header><SOAP-ENV:Body><cwmp:DownloadResponse><cwmp:Status>1</cwmp:Status><cwmp:StartTime>2014-10-24T0:4:42</cwmp:StartTime><cwmp:CompleteTime>2014-10-24T0:4:42</cwmp:CompleteTime></cwmp:DownloadResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

This TypeError will happen in genieacs-cwmp and here is the detail log info:

2015-09-07T22:46:25.109Z - TypeError: Cannot call method 'text' of undefined
    at cpeDownloadResponse (/opt/genieacs/genieacs/lib/soap.js:286:42)
    at Object.exports.request (/opt/genieacs/genieacs/lib/soap.js:469:40)
    at /opt/genieacs/genieacs/lib/cwmp.js:642:26
    at /opt/genieacs/genieacs/lib/cwmp.js:579:12
    at b (domain.js:183:18)
    at try_callback (/opt/genieacs/genieacs/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/opt/genieacs/genieacs/node_modules/redis/index.js:685:13)
    at HiredisReplyParser.<anonymous> (/opt/genieacs/genieacs/node_modules/redis/index.js:321:14)
    at HiredisReplyParser.emit (events.js:95:17)
    at HiredisReplyParser.execute (/opt/genieacs/genieacs/node_modules/redis/lib/parser/hiredis.js:43:18)

And then, even the real download is completed, the "Download" task will never end in Web GUI.

I'm using genieacs in version 1.0.4.

**Comment by zaidka** [comment]
This appears to be a client issue. The status argument is missing from the response.
