### ISSUE TITLE
genieacs-cwmp dies with RangeError

### ISSUE THREAD

**Issue by okraits** [zaidka/genieacs#137]
I just tried the latest updates in the master branch (commit dff95c3c8063f158024f2e4d45742975e4bfd8dd)  and got this error:

2016-03-07T11:26:33.273Z - RangeError: msecs must be a non-negative finite number
    at Object.exports.enroll (timers.js:156:11)
    at Socket.setTimeout (net.js:306:12)
    at /home/okraitschy/development/genieacs/lib/cwmp.js:284:32
    at getSession (/home/okraitschy/development/genieacs/lib/cwmp.js:221:12)
    at IncomingMessage.<anonymous> (/home/okraitschy/development/genieacs/lib/cwmp.js:273:12)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)

It doesn't happen in branch v1.0.

**Comment by zaidka** [comment]
Curious what version of node are you using? This doesn't crash in 0.10 so it slipped.

**Comment by okraits** [comment]
Yes, i was also surprised because my workmate using 0.10 didn't get that error.
I normally use 4.3.2 but i also got the error with 5.x.

Thank you for this quick fix.
