### ISSUE TITLE
genieacs-cwmp error

### ISSUE THREAD

**Issue by BoubakrEchieb** [zaidka/genieacs#145]
after installing **genieacs**  i try '**genieacs-cwmp**' but it give this error and i didnt .. 
**Error**: Cannot find module '**libxmljs**'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/lib/soap.js:46:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
5 Apr 11:29:06 - Worker 26150 died (1)

**Comment by zaidka** [comment]
It looks like the installation wasn't successful because the libxmljs dependency is missing. Check the installation log.

**Comment by DrumSergio** [comment]
Hi @BoubakrEchieb !

This issue tracker is just for that: for bug tracking, not for installation problems. If you want to get some help, then, post questions in the mailing list: http://lists.genieacs.com/mailman/listinfo

Thank you!

**Comment by anispirlo** [comment]
please how i can  add a device for monitoring in which file ?

**Comment by akcoder** [comment]
Please post this to the mailing list. This doesn't belong on the issue
tracker.
-dan
