### ISSUE TITLE
no service of genieacs-cwmp,genieacs-fs,genieacs-nbi

### ISSUE THREAD

**Issue by imran-linux** [zaidka/genieacs#151]
when i installed Genieacs, these service was working fine. i tried to run these to check how CPE will be added. when i start this service i get 
events.js:72
        throw er; // Unhandled 'error' event
              ^

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.1:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.3:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)

i have checked ps -ef|grep 7547, ps -ef|grep 7557 and ps -ef|grep 7567.
the service is not running already. 
please help me to make this working and suggestions are welcomed.
Please also guide me how i can add a CPE or list a CPE?

**Comment by imran-linux** [comment]
![genice](https://cloud.githubusercontent.com/assets/17451994/14999524/74301a1e-11a7-11e6-855f-d84b6bff6d99.png)

**Comment by imran-linux** [comment]
Please also post some info about the architecture of this server. Like how ruby is working in this? node. js etc? some detailed documentation would be very helpful.

**Comment by zaidka** [comment]
The error message tells that the port is already in use. You may have another process running on that same port.

**Comment by imran-linux** [comment]
Thanks replying. Now can you guide me where i can add authentication for redis in genieacs. Recently someone hacked my redis server and whole server was  compromised.

**Comment by DrumSergio** [comment]
Hi @imran-linux !

This is an issue tracker for bugs in the code. Better to take this questions to the mailing list of GenieACS: http://lists.genieacs.com/mailman/listinfo . There they can help you better if you need help.

Thank you!
