### ISSUE TITLE
Error: Parameter value type "xsd:json" not recognized

### ISSUE THREAD

**Issue by sakojamakortsyan** [zaidka/genieacs#157]
Hi,
When I genieacs-cwmp on my ubuntu server I get this error:

FFFFFF-UniFi-04%3A18%3AD6%3A6C%3A1B%3ACD: Inform (2 PERIODIC); retry count 17
Error: Parameter value type "xsd:json" not recognized.

at sanitizeParameterValue (/opt/genieacs/lib/device.js:105:17)
    at Object.set (/opt/genieacs/lib/device.js:233:32)
    at /opt/genieacs/lib/session.js:77:14
    at /opt/genieacs/lib/db.js:515:12
    at handleCallback (/opt/genieacs/node_modules/mongodb/lib/utils.js:96:12)
    at /opt/genieacs/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/opt/genieacs/node_modules/mongodb/lib/utils.js:96:12)
    at /opt/genieacs/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/opt/genieacs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/opt/genieacs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)

Can you please tell me what is the problem and how to fix it?

**Comment by DrumSergio** [comment]
This is only for bugs in GenieACS. This is a problem of a CPE sending bad parameters in its XML SOAP.
Better ask this in the mailing list. This maybe is related to XML Namespaces. They will explain it better there.

**Comment by sakojamakortsyan** [comment]
I'll do it. Thank you very much!
