### ISSUE TITLE
Copy "xmljs.node" file to another directory

### ISSUE THREAD

**Issue by DrumSergio** [zaidka/genieacs#158]
Always when installing GenieACS in an Ubuntu Server via npm, it is needed to perform the following action:

```
cp /usr/local/lib/node_modules/genieacs/node_modules/libxmljsuild/Release/obj.target/xmljs.node /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
```

Because, if you don't perform that action, the processes like "genieacs-cwmp" get stuck:

```
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/0.10.25/linux /x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)
17 Jun 15:31:23 - Worker 4359 died (8)

/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
```

Couldn't it be copied onto that folder so when you install via npm you doesn't have to perform that action?

Thanks

**Comment by zaidka** [comment]
I usually solve that issue by installing the latest version of node-gyp. IIRC, it's some kind of compatibility issue between node-gyp and libxmljs.
