### ISSUE TITLE
Error: Not implemented

### ISSUE THREAD

**Issue by luchusnet** [zaidka/genieacs#166]
When i set some parameter on genieacs gui, for example, editing the list on the device parameter list. Then, the setParameterValue show in queue list. But when the cpe send periodic event, genieacs cwmp console show this:

Error: Not implemented
at Object.rpcFault (/home/usuario/genieacs/lib/session.js:1333:9)
at f (/home/usuario/genieacs/lib/cwmp.js:467:24)

**Comment by svelep** [comment]
i have the same issue.

GenieACS version: 1.1.0-alpha
NodeJS version: 4.4.7
---
2016-08-11T14:48:05.768Z - Error: Not implemented
    at Object.rpcFault (/opt/genieacs/lib/session.js:1333:9)
    at f (/opt/genieacs/lib/cwmp.js:467:24)
    at /opt/genieacs/lib/cwmp.js:356:12
    at /opt/genieacs/lib/session.js:1377:14
    at /opt/genieacs/lib/cache.js:284:12
    at Command.<anonymous> (/opt/genieacs/lib/cache.js:106:14)
    at bound (domain.js:287:14)
    at Command.runBound (domain.js:300:12)
    at normal_reply (/opt/genieacs/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/opt/genieacs/node_modules/redis/index.js:816:9)

**Comment by zaidka** [comment]
This was fixed in a recent commit. Will close this now but feel free to reopen if you face related issues.
