### ISSUE TITLE
Failed to start genieacs-cwmp

### ISSUE THREAD

**Issue by yilcheng** [zaidka/genieacs#168]
Hi sir, it seems I encountered the same problems with issues#164 and I follow the instruction to update nodejs, then its version is v4.5.0 now. but the problem is still exist and the same, I can't start geniceacs-cwmp, could you help to advise it? Thanks.

/root/genieacs/lib/device.js:55
throw new Error(`Parameter value type "${parameterValue[1]}" not rec
^
SyntaxError: Unexpected token ILLEGAL
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/root/genieacs/lib/session.js:29:10)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:32)
26 Jul 21:35:28 - Worker 2811 died (8)

**Comment by yilcheng** [comment]
As previous docs, it said I need to use nodejs v4.4.0, but I only can get v4.5.0 now, does it matters?

**Comment by yilcheng** [comment]
Hi,

I found after installed nodejs 4.5.0 then it remove previous nodejs and nodejs-legacy automatically.
and after that, I can't do npm install libxmljs@0.11.0, it always failed. And I tried to re-install nodejs-legacy.
It failed to install it, does it mean nodejs 4.5.0 is not compatible with genieacs? But I can't find 4.4.0 for verification, could you advise it?

**Comment by yilcheng** [comment]
I finally fixed it by "npm install libxmljs@0.16.1", then I can successfully re-install libxmljs and genieacs
Don't know why, for you reference.
