### ISSUE TITLE
500 Internal Server Error, TypeError : Cannot read property  'attr' of undefined 

### ISSUE THREAD

**Issue by yilcheng** [zaidka/genieacs#169]
Hi,

i am getting response from CPE POST and returned a response status of 500 Internal Server Error.

TypeError : Cannot read property  'attr' of undefined 

can anyone help me to check this issue. Does it mean I post a parameter which ACS server don't recognize?

**Comment by zaidka** [comment]
Looks like a bug. Can you show the error stack trace? Make sure your repo has the latest updates.

**Comment by yilcheng** [comment]
Below is console log for you reference, and I just got the repo 3 days ago, I think it's latest.
For genieacs, it's 1.1.0 alpha, for gui, I am not sure how to check the version.

--
9 Sep 08:42:04 - 0014A4-CPE_test-0123456789: Inform (0 BOOTSTRAP,1 BOOT); retry count 0
9 Sep 08:42:04 - 0014A4-CPE_test-0123456789: Started task refreshObject(57d2055cf978613e0ac88e41)
(node) util.error is deprecated. Use console.error instead.
2016-09-09T00:42:12.737Z - TypeError: Cannot read property 'attr' of undefined
    at parameterValueList (/usr/lib/node_modules/genieacs/lib/soap.js:137:31)
    at cpeGetParameterValuesResponse (/usr/lib/node_modules/genieacs/lib/soap.js:190:20)
    at Object.exports.request (/usr/lib/node_modules/genieacs/lib/soap.js:448:40)
    at /usr/lib/node_modules/genieacs/lib/cwmp.js:642:26
    at /usr/lib/node_modules/genieacs/lib/cwmp.js:579:12
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at try_callback (/usr/lib/node_modules/genieacs/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/usr/lib/node_modules/genieacs/node_modules/redis/index.js:685:13)
    at HiredisReplyParser.<anonymous> (/usr/lib/node_modules/genieacs/node_modules/redis/index.js:321:14)

2016-09-09T08:42:12.771+0800 [conn20] end connection 127.0.0.1:37700 (39 connections now open)
2016-09-09T08:42:12.773+0800 [conn24] end connection 127.0.0.1:37705 (38 connections now open)
2016-09-09T08:42:12.780+0800 [conn22] end connection 127.0.0.1:37703 (37 connections now open)
2016-09-09T08:42:12.781+0800 [conn23] end connection 127.0.0.1:37704 (37 connections now open)
2016-09-09T08:42:12.789+0800 [conn21] end connection 127.0.0.1:37702 (37 connections now open)
9 Sep 08:42:12 - Worker 2622 died (0)
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
2016-09-09T08:42:13.818+0800 [initandlisten] connection accepted from 127.0.0.1:37796 #55 (36 connections now open)
2016-09-09T08:42:13.857+0800 [conn55] end connection 127.0.0.1:37796 (35 connections now open)
2016-09-09T08:42:13.864+0800 [initandlisten] connection accepted from 127.0.0.1:37797 #56 (37 connections now open)
2016-09-09T08:42:13.868+0800 [initandlisten] connection accepted from 127.0.0.1:37798 #57 (37 connections now open)
2016-09-09T08:42:13.869+0800 [initandlisten] connection accepted from 127.0.0.1:37799 #58 (38 connections now open)
2016-09-09T08:42:13.869+0800 [initandlisten] connection accepted from 127.0.0.1:37800 #59 (39 connections now open)
2016-09-09T08:42:13.869+0800 [initandlisten] connection accepted from 127.0.0.1:37801 #60 (40 connections now open)
9 Sep 08:42:13 - Worker 2912 listening to 0.0.0.0:7547

**Comment by yilcheng** [comment]
Hey Sir,

Did you have update for this issue?

**Comment by zaidka** [comment]
That's a device issue. This might help: https://github.com/zaidka/genieacs/issues/17#issuecomment-45466577

**Comment by yilcheng** [comment]
Hi Zaidka,

I also found this root cause, thanks for your help.
It indeed fixed this issue.
