### ISSUE TITLE
Worker dies on connect (Sphairon based CPE) - soap.js

### ISSUE THREAD

**Issue by christianheyl** [zaidka/genieacs#17]
Re-checked my configuration, found some minor mistakes, but it's correct now. CPE connects via WAN to ACS (LAN didn't work -> CPE's fault). When the CPE connects to the ACS, I get the following error messages displayed

<pre><code>
/home/chris/genieacs/lib/soap.js:124
    valueType = e.get('Value').attr('type').value().trim();
                                            ^
TypeError: Cannot call method 'value' of null
    at parameterValueList (/home/chris/genieacs/lib/soap.js:124:45)
    at acsInform (/home/chris/genieacs/lib/soap.js:279:20)
    at Object.exports.request (/home/chris/genieacs/lib/soap.js:421:39)
    at IncomingMessage.<anonymous> (/home/chris/genieacs/lib/cwmp.js:675:24)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
6 Jun 18:29:00 - Worker 5112 died (8)
6 Jun 18:30:02 - Worker 5139 listening to 0.0.0.0:7547
6 Jun 18:30:02 - Worker 5139 listening to 0.0.0.0:7548
</code></pre>

I traced the communication to ACS with tcpdump on the cpe. I did sent you the trace file via mail

The only thing that is different to my other CPEs is, that all value tags look like that

<pre><code>
...
            &lt;ParameterList SOAP-ENC:arrayType="cwmp:ParameterValueStruct[7]"&gt; 
                &lt;ParameterValueStruct&gt; 
                  &lt;Name&gt;InternetGatewayDevice.DeviceInfo.SpecVersion&lt;/Name&gt; 
                  &lt;Value&gt;1.0 &lt;/Value&gt; 
                &lt;/ParameterValueStruct&gt;
...
</code></pre>

Do you have any idea, why this is happening? Is it because the value tags don't have something like "&lt;Value xsi:type="xsd:string"&gt;" in it, just plain "&lt;value&gt;"? I don't know if that is just a view problem, because i copied the data (raw) from wireshark.

**Comment by Vozglobal** [comment]
Hi
2016-08-08T10:17:24.442Z - TypeError: Cannot call method 'attr' of undefined                                          
    at parameterValueList (/usr/lib/node_modules/genieacs/lib/soap.js:137:32)                                         
    at cpeGetParameterValuesResponse (/usr/lib/node_modules/genieacs/lib/soap.js:190:20)                              
    at Object.exports.request (/usr/lib/node_modules/genieacs/lib/soap.js:448:40)                                     
    at /usr/lib/node_modules/genieacs/lib/cwmp.js:642:26                                                              
    at /usr/lib/node_modules/genieacs/lib/cwmp.js:579:12                                                              
    at b (domain.js:183:18)                                                                                           
    at try_callback (/usr/lib/node_modules/genieacs/node_modules/redis/index.js:592:9)                                
    at RedisClient.return_reply (/usr/lib/node_modules/genieacs/node_modules/redis/index.js:685:13)                   
    at HiredisReplyParser.<anonymous> (/usr/lib/node_modules/genieacs/node_modules/redis/index.js:321:14)             
    at HiredisReplyParser.emit (events.js:95:17)                

My funtion parameters list is:

parameterValueList = function(xml) {
  var e, err, error, j, len, name, ref1, value, valueList, valueType;
  valueList = [];
  ref1 = xml.find('ParameterValueStruct');
  for (j = 0, len = ref1.length; j < len; j++) {
    e = ref1[j];
    valueType = e.get('Value').attr('type').value().trim();
    name = e.get('Name').text().trim();
    value = e.get('Value').text().trim();
    try {
      switch (valueType) {
        case 'xsd:boolean':
          value = Boolean(JSON.parse(value));
          break;
        case 'xsd:unsignedInt':
          value = JSON.parse(value);
          break;
        case 'xsd:int':
          value = JSON.parse(value);
      }
    } catch (error) {
      err = error;
      value = null;
    }
    valueList.push([name, value, valueType]);
  }
  return valueList;
};

Do you have any idea, why this is happening?
