### ISSUE TITLE
some errors during inform

### ISSUE THREAD

**Issue by zhayun** [zaidka/genieacs#174]
When the CPE send inform to the genieacs, the genieacs-cwmp got some error messages as following,
And I also can not see any device on the management WEB UI of genieacs by port 3000.

23 Sep 05:06:14 - 00904C-96318REF-00904c888888: Inform (1 BOOT,4 VALUE CHANGE); retry count 0
(node) util.error is deprecated. Use console.error instead.
2016-09-23T12:06:14.752Z - TypeError: Cannot read property '0' of undefined
    at Object.saveDevice (/opt/genieacs/lib/db.js:627:80)
    at Object.end (/opt/genieacs/lib/session.js:1789:13)
    at sendRpcRequest (/opt/genieacs/lib/cwmp.js:344:13)
    at /opt/genieacs/lib/cwmp.js:263:16
    at f (/opt/genieacs/lib/session.js:758:16)
    at runDeclarations (/opt/genieacs/lib/session.js:600:10)
    at Object.rpcRequest (/opt/genieacs/lib/session.js:699:10)
    at /opt/genieacs/lib/cwmp.js:256:22
    at f (/opt/genieacs/lib/session.js:679:20)
    at runProvisions (/opt/genieacs/lib/session.js:535:10)

/opt/genieacs/lib/cwmp.js:425
            throw err;
            ^
AbortError: SETEX can't be processed. The connection is already closed.
    at handle_offline_command (/opt/genieacs/node_modules/redis/index.js:843:15)
    at RedisClient.internal_send_command (/opt/genieacs/node_modules/redis/index.js:873:9)
    at RedisClient.setex (/opt/genieacs/node_modules/redis/lib/commands.js:62:25)
    at /opt/genieacs/lib/cwmp.js:423:31
    at Object.serialize (/opt/genieacs/lib/session.js:1785:10)
    at Socket.<anonymous> (/opt/genieacs/lib/cwmp.js:419:28)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)
23 Sep 05:06:14 - Worker 2824 died (1)
23 Sep 05:06:15 - Worker 3320 listening to 0.0.0.0:7547

**Comment by zaidka** [comment]
Hmm, not sure. I'm currently making some changes and cleanups there anyway so I'll let you know when that's done to try again.

**Comment by rcmajhi** [comment]
hi  zaidka ,
I am also facing the same same issue as described in the above ticket. 
Kindly guide  to resolve the issue. 
Looking forward for your co-operation and support.

**Comment by agabellini** [comment]
Hello,

with today's commit the error is gone.

**Comment by zhayun** [comment]
it's OK with commit #600ca58b99c27cbe1b861bd859685150206412b2
