### ISSUE TITLE
Error: Unknown configuration type add_object

### ISSUE THREAD

**Issue by mrakotiq** [zaidka/genieacs#180]
Hi,
I test the current version 1.1.0-alpha and I found this bug. If it is a bug?
If the preset contains type add_object, CWMP process ends with:

```
/opt/genieacs/node_modules/mongodb/lib/utils.js:99
    process.nextTick(function() { throw err; });
                                  ^
Error: Unknown configuration type add_object
    at /opt/genieacs/lib/cache.js:173:23
    at handleCallback (/opt/genieacs/node_modules/mongodb/lib/utils.js:96:56)
    at /opt/genieacs/node_modules/mongodb/lib/cursor.js:853:16
    at handleCallback (/opt/genieacs/node_modules/mongodb-core/lib/cursor.js:172:5)
    at setCursorDeadAndNotified (/opt/genieacs/node_modules/mongodb-core/lib/cursor.js:507:3)
    at nextFunction (/opt/genieacs/node_modules/mongodb-core/lib/cursor.js:655:7)
    at Cursor.next [as _next] (/opt/genieacs/node_modules/mongodb-core/lib/cursor.js:696:3)
    at fetchDocs (/opt/genieacs/node_modules/mongodb/lib/cursor.js:849:10)
    at /opt/genieacs/node_modules/mongodb/lib/cursor.js:872:7
    at handleCallback (/opt/genieacs/node_modules/mongodb-core/lib/cursor.js:172:5)
```

I have never found mention about add_object in source code. This function has been removed from the new version?

**Comment by mrakotiq** [comment]
I found another similar issue. If I try add object via genieacs-gui (device -> device parameters -> path -> add)
I get this exception:
`2016-11-02T12:06:34.589Z - Error: Task name not recognized. Task.name:addObject
    at /opt/genieacs/lib/cwmp.js:333:17
    at Object.rpcRequest (/opt/genieacs/lib/session.js:701:12)
    at nextRpc (/opt/genieacs/lib/cwmp.js:270:18)
    at f (/opt/genieacs/lib/cwmp.js:618:16)
    at getSession (/opt/genieacs/lib/cwmp.js:391:12)
    at IncomingMessage.<anonymous> (/opt/genieacs/lib/cwmp.js:478:12)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)

(node:30745) DeprecationWarning: util.error is deprecated. Use console.error instead.

/opt/genieacs/lib/cwmp.js:425
            throw err;
            ^
`
For clarity "Task.name:addObject"  is my debug code not present in git.

**Comment by zaidka** [comment]
Adding or deleting instances is currently only supported in scripts. Compatibility shim for download tasks is yet to be implemented. Will update this thread when that's done.

**Comment by mberniz** [comment]
Hello, I have the same problem.

When you mean adding or deleting instances is currently only supported in scripts? What do you mean? How can I make an script to do that?

Thanks in advance,

Miguel

**Comment by DrumSergio** [comment]
Only to follow this issue, @zaidka : Is it implemented now? If yes, then close.

@mberniz , I think Zaid wants to say that the functionality is available via a JS script, which you have to write, and then implement via "Presets" tab.

**Comment by mberniz** [comment]
Thanks Sergio, 

Unfortunately we do not have JS resources, but thank you for the tip. I am really looking for 1.1 to come out with the things not working now (presets creation through the API). 

Kind regards, 

Miguel 



----- Original Message -----
