### ISSUE TITLE
genieacs-cwmp start || Error: bind EACCES

### ISSUE THREAD

**Issue by ibrahimelsawy** [zaidka/genieacs#186]
Hi

it was working properly and CPEs was detected but after last restart for VM **genieacs-cwmp start** gives below errors and CPEs cant be detected on the GenieACS server. i tried recommendation to kill node sessions and reloading the VM but with no resolution. appreciate your support

planning@planning:~$ genieacs-cwmp start

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EACCES
    at errnoException (net.js:901:11)
    at net.js:1069:30
    at Object.1:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
16 Nov 00:46:14 - Worker 16377 died (8)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EACCES
    at errnoException (net.js:901:11)
    at net.js:1069:30
    at Object.4:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
16 Nov 00:46:14 - Worker 16381 died (8)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EACCES
    at errnoException (net.js:901:11)
    at net.js:1069:30
    at Object.2:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
16 Nov 00:46:14 - Worker 16378 died (8)

**Comment by zaidka** [comment]
Doesn't look like a bug but an issue with your setup. I'll close this but you may post to the mailing list instead.
