### ISSUE TITLE
NodeJS 5 support

### ISSUE THREAD

**Issue by JamesHarrison** [zaidka/genieacs#190]
GenieACS does not currently support NodeJS 5.x. Issues with "use strict" being required in provisions, but also some errors in device.js:

```

Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: (node) util.error is deprecated. Use console.error instead.
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: 2016-12-05T16:02:33.236Z - TypeError: deviceData.timestamps.get is not a function
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at Object.set (/opt/genieacs/lib/device.js:221:48)
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at /opt/genieacs/lib/session.js:298:14
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at /opt/genieacs/lib/session.js:106:14
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at /opt/genieacs/lib/db.js:464:14
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at handleCallback (/opt/genieacs/node_modules/mongodb/lib/utils.js:96:12)
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at /opt/genieacs/node_modules/mongodb/lib/collection.js:1395:5
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at handleCallback (/opt/genieacs/node_modules/mongodb/lib/utils.js:96:12)
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at /opt/genieacs/node_modules/mongodb/lib/cursor.js:675:5
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at handleCallback (/opt/genieacs/node_modules/mongodb-core/lib/cursor.js:165:5)
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: at setCursorNotified (/opt/genieacs/node_modules/mongodb-core/lib/cursor.js:505:3)
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: 5 Dec 16:02:33 - Worker 3371 died (0)
Dec 05 16:02:33 hostname-masked genieacs-cwmp[992]: 5 Dec 16:02:33 - Worker 3422 listening to 0.0.0.0:7547

```

**Comment by DrumSergio** [comment]
Hi @JamesHarrison !

Currently, GenieACS v1.0 supports Node version 0.10.X (as far as I've tested) and v1.1 is targeted to work with Node version 6.X

I think this is not an issue... We can close it
