### ISSUE TITLE
Error when run genieacs-cwmp

### ISSUE THREAD

**Issue by giln344** [zaidka/genieacs#201]
Hi,

When i run the command "npm install" im getting the error:

**"node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v11-linux-x64.tar.gz "**

**"node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@0.10.48 (node-v11 ABI) (falling back to source compile with node-gyp) "**

after he finished i'm trying to run ./bin/genieacs-cwmp i'm getting that error:

**/opt/genieacs/lib/config.js:203
    } else if (name.startsWith(n + "-")) {
                    ^
TypeError: Object MONGODB_CONNECTION_URL has no method 'startsWith'
    at setConfig (/opt/genieacs/lib/config.js:203:21)
    at Object.<anonymous> (/opt/genieacs/lib/config.js:246:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/genieacs/lib/cluster.js:21:10)
    at Module._compile (module.js:456:26)**

Please help.

**Comment by DrumSergio** [comment]
Hi @giln344<mailto:notifications@github.com> !

Please, use this issue tracker to post about bugs in the code, not installation problems.
Please post it in the mailing list: http://lists.genieacs.com

Anyway, we would need more info about what you've installed and how in order to help you better.

Thank you!

Obtener Outlook para Android<https://aka.ms/ghei36>


________________________________

**Comment by giln344** [comment]
I have installed:
nodejs Version 0.10.48
mongodb Version 2.4.14
redis Version 2.4.10
after that i have installed GenieACS
