### ISSUE TITLE
stale mongodb connections

### ISSUE THREAD

**Issue by ssikburgess** [zaidka/genieacs#206]
I am using genieacs v1.0 and it works great for the most part. However, when running performance tests using genieacs-simulator, I am running into some issues. I am simulating 1000 devices running with "genieacs-sim -p 1000 -w 0". This is able to run for about a minute, until I start getting timeout errors.

Error: Socket timed out
    at ClientRequest.<anonymous> (~genieacs-sim/simulator.js:91:11)

After stopping genieacs-sim, the mongod system process continues to use 90% cpu even though it is apparently doing nothing. At this point, the application becomes unusable until mongod is restarted. I still see informs getting logged, I get timeouts when trying to view the gui, or query a list of devices via nbi. After restarting mongod, things function as normal, but I get the following genieacs-cwmp errors directly after

===========================

2017-02-14T22:02:08.355Z - MongoError: Connection Closed By Application
    at Object.toError (/usr/local/lib/node_modules/genieacs/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at Server.close (/usr/local/lib/node_modules/genieacs/node_modules/mongodb/lib/mongodb/connection/server.js:188:38)
    at Db.close (/usr/local/lib/node_modules/genieacs/node_modules/mongodb/lib/mongodb/db.js:360:21)
    at Object.disconnect (/usr/local/lib/node_modules/genieacs/lib/db.js:134:19)
    at Server.<anonymous> (/usr/local/lib/node_modules/genieacs/lib/server.js:62:19)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1277:10
    at process._tickDomainCallback (node.js:492:13)

2017-02-14T22:02:08.356Z - Error: channel closed
    at process.target.send (child_process.js:406:26)
    at Worker.send (cluster.js:406:21)
    at sendInternalMessage (cluster.js:399:10)
    at Worker.disconnect (cluster.js:479:5)
    at Domain.<anonymous> (/usr/local/lib/node_modules/genieacs/lib/server.js:59:14)
    at Domain.emit (events.js:95:17)
    at process._fatalException (node.js:263:29)

===========================

I tested with v2 of npm mongodb module, and I did not see the same issues.

Software versions
==============
NodeJS v0.10.40
GenieACS v1.0
MongoDB v2.6.12
npm mongodb v1.4.40

**Comment by ssikburgess** [comment]
UPDATE: mongod was freezing up due to device update queries hanging. I added a socketTimeout in the mongodb connection and this was no longer an issue.

  return mongodb.MongoClient.connect(config.get('MONGODB_CONNECTION_URL'), {
    db: {
      w: 1
    },
    server: {
      autoReconnect: true,
      socketTimeoutMS: 50
    }

**Comment by zaidka** [comment]
Not sure what you were expecting when you spawned a 1000 devices at once :) There's a mechanism to refuse new connections when under load but it's not perfect. Should be good enough for most real world cases though.
