### ISSUE TITLE
Error connecting to CPEs that require connection auth

### ISSUE THREAD

**Issue by akcoder** [zaidka/genieacs#209]
It appears that the address isn't being passed in correctly. I did a console.log on the arguments:

{ '0': 'RA:',
  '1': 'username',
  '2': 'somePassword',
  '3': [Function] }

2017-02-22T17:15:22.697Z [ERROR] Uncaught exception; exceptionName="RangeError" exceptionMessage="Port should be > 0 and < 65536" exceptionStack="RangeError: Port should be > 0 and < 65536
at Socket.send (dgram.js:338:11)
at udpConReq (/opt/genieacs/lib/api-functions.js:73:17)
at conReq (/opt/genieacs/lib/api-functions.js:189:9)
at /opt/genieacs/lib/api-functions.js:212:12
at handleCallback (/opt/genieacs/node_modules/mongodb/lib/utils.js:95:56)
at /opt/genieacs/node_modules/mongodb/lib/collection.js:1406:5
at handleCallback (/opt/genieacs/node_modules/mongodb/lib/utils.js:95:56)
at /opt/genieacs/node_modules/mongodb/lib/cursor.js:674:5
at handleCallback (/opt/genieacs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
at nextFunction (/opt/genieacs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:682:5)

**Comment by akcoder** [comment]
Upon further digging, the client was sending down "RA:" as the InternetGatewayDevice.ManagementServer.UDPConnectionRequestAddress value. I modified api-functions and removed InternetGatewayDevice.ManagementServer.UDPConnectionRequestAddress from the projection and updated the client value to null, then re-compiled the code.

Not sure how to handle this. Maybe catch the error and fallback to another connection method?

**Comment by zaidka** [comment]
Fixed in a9c8bbe21b103553d3f8160a8e37e8a5b017cf67.
