### ISSUE TITLE
genieacs-cwmp  wont start on Debian 8

### ISSUE THREAD

**Issue by cubicalmonkey** [zaidka/genieacs#210]
I cant seem to get genieacs-cwmp to start in Debian.
Sorry if this would be something better suited for the mailing list.
```
 ./genieacs-cwmp
2017-03-01T15:21:33.636Z [INFO] GenieACS (genieacs-cwmp) starting; pid=19670 version="1.1.0-alpha" dependencies="node@4.6.2,hiredis@0.5.0,later@1.2.0,libxmljs@0.18.4,mongodb@2.2.24,redis@2.6.5,seedrandom@2.4.2" config="CONFIG_DIR=/opt/genieacs-master/config,MONGODB_CONNECTION_URL=mongodb://127.0.0.1/genieacs,REDIS_PORT=6379,REDIS_HOST=127.0.0.1,CWMP_INTERFACE=0.0.0.0,CWMP_PORT=7547,CWMP_SSL=false,NBI_INTERFACE=0.0.0.0,NBI_PORT=7557,FS_INTERFACE=0.0.0.0,FS_PORT=7567,FS_IP=192.168.0.1,LOG_INFORMS=true,DEBUG=false,REDIS_DB=0,CWMP_WORKER_PROCESSES=0,CWMP_LOG_FILE=,CWMP_ACCESS_LOG_FILE=,NBI_WORKER_PROCESSES=0,NBI_SSL=false,NBI_LOG_FILE=,NBI_ACCESS_LOG_FILE=,FS_WORKER_PROCESSES=0,FS_SSL=false,FS_LOG_FILE=,FS_ACCESS_LOG_FILE=,DOWNLOAD_TIMEOUT=3600,EXT_TIMEOUT=3000,PRESETS_CACHE_DURATION=86400,RETRY_DELAY=300,SESSION_TIMEOUT=30,CONNECTION_REQUEST_TIMEOUT=2000,GET_PARAMETER_NAMES_DEPTH_THRESHOLD=0,TASK_PARAMETERS_BATCH_SIZE=32,MAX_DEPTH=16,LOG_FORMAT=simple,ACCESS_LOG_FORMAT=,XML_RECOVER=false,XML_IGNORE_ENC=false,XML_FORMAT=false,XML_NO_DECL=false,XML_NO_EMPTY=false,XML_IGNORE_NAMESPACE=false,DEVICE_ONLINE_THRESHOLD=4000"
2017-03-01T15:21:33.644Z [WARN] This is a development branch of GenieACS. DO NOT use in production.


/opt/genieacs-master/lib/path-set.js:111
  find(pattern, superset = false, subset = false, depth = pattern.length) {
                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/genieacs-master/lib/session.js:33:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
2017-03-01T15:21:34.441Z [ERROR] Worker died; pid=19692 exitCode=1
/opt/genieacs-master/lib/path-set.js:111
  find(pattern, superset = false, subset = false, depth = pattern.length) {
```

**Comment by DrumSergio** [comment]
Hi @cubicalmonkey !

Better to post it in the [mailing list of GenieACS](http://lists.genieacs.com/), with the Node version you're using right now, along with the MongoDB and Redis versions. It seems like a bug, but it will help us to know better your system and if is it really a bug. For me, right now I have an instance in Debian 8 working with GenieACS v1.1

Thank you!

**Comment by zaidka** [comment]
You seem to be using Node v4. You need to upgrade to v6.
