### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by erindru** [zaidka/genieacs#223]
When receiving the following SOAP request from a Mikrotik device:

```xml
<soapenv:Envelope xmlns:soap='http://schemas.xmlsoap.org/soap/encoding/' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:cwmp='urn:dslforum-org:cwmp-1-0' xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'><soapenv:Body><cwmp:Inform><DeviceId><Manufacturer>MikroTik</Manufacturer><OUI>E48D8C</OUI><ProductClass>CHR</ProductClass><SerialNumber></SerialNumber></DeviceId><Event soap:arrayType='cwmp:EventStruct[2]'><EventStruct><EventCode>2 PERIODIC</EventCode><CommandKey></CommandKey></EventStruct><EventStruct><EventCode>1 BOOT</EventCode><CommandKey></CommandKey></EventStruct></Event><MaxEnvelopes>1</MaxEnvelopes><CurrentTime>2017-04-02T06:35:56+00:00</CurrentTime><RetryCount>2</RetryCount><ParameterList soap:arrayType='cwmp:ParameterValueStruct[7]'><ParameterValueStruct><Name>Device.RootDataModelVersion</Name><Value xsi:type='xsd:string'>2.11</Value></ParameterValueStruct><ParameterValueStruct><Name>Device.DeviceInfo.HardwareVersion</Name><Value xsi:type='xsd:string'>v1.0</Value></ParameterValueStruct><ParameterValueStruct><Name>Device.DeviceInfo.SoftwareVersion</Name><Value xsi:type='xsd:string'>6.38.5</Value></ParameterValueStruct><ParameterValueStruct><Name>Device.DeviceInfo.ProvisioningCode</Name><Value xsi:type='xsd:string'></Value></ParameterValueStruct><ParameterValueStruct><Name>Device.ManagementServer.ParameterKey</Name><Value xsi:type='xsd:string'></Value></ParameterValueStruct><ParameterValueStruct><Name>Device.ManagementServer.ConnectionRequestURL</Name><Value xsi:type='xsd:string'>http://192.168.1.157:7547/</Value></ParameterValueStruct><ParameterValueStruct><Name>Device.ManagementServer.AliasBasedAddressing</Name><Value xsi:type='xsd:boolean'>0</Value></ParameterValueStruct></ParameterList></cwmp:Inform></soapenv:Body></soapenv:Envelope>
```

The CWMP process exits with:

```bash
2017-04-02T05:10:23.930Z [ERROR] Uncaught exception; exceptionName="TypeError" exceptionMessage="Cannot read property 'text' of undefined" exceptionStack="TypeError: Cannot read property 'text' of undefined\n    at Object.request (/src/genieacs/lib/soap.js:465:94)\n    at f (/src/genieacs/lib/cwmp.js:749:20)\n    at getSession (/src/genieacs/lib/cwmp.js:649:12)\n    at IncomingMessage.<anonymous> (/src/genieacs/lib/cwmp.js:743:12)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:188:7)\n    at endReadableNT (_stream_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)"
2017-04-02T05:10:33.938Z [ERROR] Worker died; pid=463 exitCode=0
```

If I change line 465 of `lib/soap.js` to:

```javascript
  var rpcId = xml.get("/soap-env:Envelope/soap-env:Header/cwmp:ID", NAMESPACES[rpc.cwmpVersion]);
  rpc.id = (rpcId) ? rpcId.text() : null;
```

Then I am able to prevent the error and the device shows in the UI, but im not sure what else breaks

**Comment by zaidka** [comment]
The ID is used in to map requests to their responses. If you don't see any exception after this change then you're good.
