### ISSUE TITLE
Cannot update '_tags' and '_tags' at the same time

### ISSUE THREAD

**Issue by ekesseler** [zaidka/genieacs#229]
While using a preset, that simultaneously removes a tag and adds a tag, there is an exception thrown:

`2017-04-21T10:14:47.727Z [INFO] 192.168.3.233 ...: Inform; cpeRequestId="2073731608" informEvent="1 BOOT" informRetryCount=0
2017-04-21T10:14:47.742Z [ERROR] Uncaught exception; exceptionName="MongoError" exceptionMessage="Cannot update '_tags' and '_tags' at the same time" exceptionStack="MongoError: Cannot update '_tags' and '_tags' at the same time\n    at Function.MongoError.create (/opt/genieacs/node_modules/mongodb-core/lib/error.js:31:11)\n    at toError (/opt/genieacs/node_modules/mongodb/lib/utils.js:139:22)\n    at /opt/genieacs/node_modules/mongodb/lib/collection.js:1060:67\n    at /opt/genieacs/node_modules/mongodb-core/lib/connection/pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)"`

![start-monitoring](https://cloud.githubusercontent.com/assets/11627677/25273626/e451f132-268c-11e7-9a0f-599c312f9ed1.png)

**Comment by ekesseler** [comment]
current master branch is used, please let me know if you need more info

**Comment by ekesseler** [comment]
@zaidka thanks for the quick fix
