### ISSUE TITLE
error when using presets to add/delete objects

### ISSUE THREAD

**Issue by testgenieacs** [zaidka/genieacs#245]
2017-07-19T01:51:21.480Z [INFO] Worker listening; pid=24881 address="192.168.2.5" port=80
2017-07-19T01:55:21.220Z [ERROR] Uncaught exception; exceptionName="TypeError" exceptionMessage="Cannot read property 'length' of undefined" exceptionStack="TypeError: Cannot read property 'length' of undefined\n    at /home/mint/Desktop/Genieacs_new/genieacs/lib/cache.js:197:48\n    at /home/mint/Desktop/Genieacs_new/genieacs/lib/cache.js:202:25\n    at handleCallback (/home/mint/Desktop/Genieacs_new/genieacs/node_modules/mongodb/lib/utils.js:120:56)\n    at /home/mint/Desktop/Genieacs_new/genieacs/node_modules/mongodb/lib/cursor.js:860:16\n    at handleCallback (/home/mint/Desktop/Genieacs_new/genieacs/node_modules/mongodb-core/lib/cursor.js:171:5)\n    at setCursorDeadAndNotified (/home/mint/Desktop/Genieacs_new/genieacs/node_modules/mongodb-core/lib/cursor.js:505:3)\n    at nextFunction (/home/mint/Desktop/Genieacs_new/genieacs/node_modules/mongodb-core/lib/cursor.js:651:7)\n    at Cursor.next [as _next] (/home/mint/Desktop/Genieacs_new/genieacs/node_modules/mongodb-core/lib/cursor.js:692:3)\n    at fetchDocs (/home/mint/Desktop/Genieacs_new/genieacs/node_modules/mongodb/lib/cursor.js:856:10)\n    at /home/mint/Desktop/Genieacs_new/genieacs/node_modules/mongodb/lib/cursor.js:879:7"
2017-07-19T01:55:51.228Z [ERROR] Worker died; pid=22721 exitCode=1
2017-07-19T01:55:51.707Z [INFO] Worker listening; pid=28500 address="192.168.2.5" port=80

**Comment by vbashkirtsev** [comment]
Basically the issue is that your object you reference in preset does not have any keys. Just mark at least one parameter in object as a key and problem will go away.

But still this should be considered as a bug in GenieACS: it should not fail if no keys are set in object.
