### ISSUE TITLE
rails always show ActionController::RoutingError (No route matches [POST] "/") repeatly

### ISSUE THREAD

**Issue by githubhellowolf** [zaidka/genieacs#250]
$ mongod --version
db version v2.6.12

$ ruby -v
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]

$ redis-server -v
Redis server v=3.2.10 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=5fc30b4ab0be6cb6

$ rails -v
Rails 5.0.0

$ genieacs-cwmp
2017-08-04T01:21:06.332Z [INFO] GenieACS (genieacs-cwmp) starting; pid=4974 version="1.1.1" dependencies="node@6.11.2,hiredis@0.5.0,later@1.2.0,libxmljs@0.18.7,mongodb@2.2.30,redis@2.7.1,seedrandom@2.4.3" config="CONFIG_DIR=/usr/local/lib/node_modules/genieacs/config,MONGODB_CONNECTION_URL=mongodb://192.168.1.11/genieacs,REDIS_PORT=6379,REDIS_HOST=192.168.1.11,CWMP_INTERFACE=0.0.0.0,CWMP_PORT=7547,CWMP_SSL=false,NBI_INTERFACE=0.0.0.0,NBI_PORT=7557,FS_INTERFACE=0.0.0.0,FS_PORT=7567,FS_HOSTNAME=192.168.1.11,FS_IP=192.168.1.11,LOG_INFORMS=true,DEBUG=false,REDIS_DB=0,CWMP_WORKER_PROCESSES=0,CWMP_LOG_FILE=,CWMP_ACCESS_LOG_FILE=,NBI_WORKER_PROCESSES=0,NBI_SSL=false,NBI_LOG_FILE=,NBI_ACCESS_LOG_FILE=,FS_WORKER_PROCESSES=0,FS_SSL=false,FS_LOG_FILE=,FS_ACCESS_LOG_FILE=,DOWNLOAD_TIMEOUT=3600,EXT_TIMEOUT=3000,MAX_CACHE_TTL=86400,RETRY_DELAY=300,SESSION_TIMEOUT=30,CONNECTION_REQUEST_TIMEOUT=2000,GPN_NEXT_LEVEL=0,GPV_BATCH_SIZE=32,MAX_DEPTH=16,LOG_FORMAT=simple,ACCESS_LOG_FORMAT=,XML_RECOVER=false,XML_IGNORE_ENC=false,XML_FORMAT=false,XML_NO_DECL=false,XML_NO_EMPTY=false,XML_IGNORE_NAMESPACE=false,DEVICE_ONLINE_THRESHOLD=4000"
2017-08-04T01:21:06.753Z [INFO] Worker listening; pid=5014 address="0.0.0.0" port=7547

$ genieacs-nbi 
2017-08-04T01:21:18.724Z [INFO] GenieACS (genieacs-nbi) starting; pid=5063 version="1.1.1" dependencies="node@6.11.2,hiredis@0.5.0,later@1.2.0,libxmljs@0.18.7,mongodb@2.2.30,redis@2.7.1,seedrandom@2.4.3" config="CONFIG_DIR=/usr/local/lib/node_modules/genieacs/config,MONGODB_CONNECTION_URL=mongodb://192.168.1.11/genieacs,REDIS_PORT=6379,REDIS_HOST=192.168.1.11,CWMP_INTERFACE=0.0.0.0,CWMP_PORT=7547,CWMP_SSL=false,NBI_INTERFACE=0.0.0.0,NBI_PORT=7557,FS_INTERFACE=0.0.0.0,FS_PORT=7567,FS_HOSTNAME=192.168.1.11,FS_IP=192.168.1.11,LOG_INFORMS=true,DEBUG=false,REDIS_DB=0,CWMP_WORKER_PROCESSES=0,CWMP_LOG_FILE=,CWMP_ACCESS_LOG_FILE=,NBI_WORKER_PROCESSES=0,NBI_SSL=false,NBI_LOG_FILE=,NBI_ACCESS_LOG_FILE=,FS_WORKER_PROCESSES=0,FS_SSL=false,FS_LOG_FILE=,FS_ACCESS_LOG_FILE=,DOWNLOAD_TIMEOUT=3600,EXT_TIMEOUT=3000,MAX_CACHE_TTL=86400,RETRY_DELAY=300,SESSION_TIMEOUT=30,CONNECTION_REQUEST_TIMEOUT=2000,GPN_NEXT_LEVEL=0,GPV_BATCH_SIZE=32,MAX_DEPTH=16,LOG_FORMAT=simple,ACCESS_LOG_FORMAT=,XML_RECOVER=false,XML_IGNORE_ENC=false,XML_FORMAT=false,XML_NO_DECL=false,XML_NO_EMPTY=false,XML_IGNORE_NAMESPACE=false,DEVICE_ONLINE_THRESHOLD=4000"
2017-08-04T01:21:19.085Z [INFO] Worker listening; pid=5097 address="0.0.0.0" port=7557

$ sudo rails s -b 192.168.1.11
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://192.168.1.11:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.5.2 (ruby 2.3.4-p301), codename: Amateur Raccoon Rocketry
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://192.168.1.11:3000
Use Ctrl-C to stop
Started POST "/" for 192.168.1.254 at 2017-08-04 09:23:29 +0800
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
ActionController::RoutingError (No route matches [POST] "/"):
actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.3.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0) lib/rails/engine.rb:522:in `call'
puma (3.5.2) lib/puma/configuration.rb:225:in `call'
puma (3.5.2) lib/puma/server.rb:569:in `handle_request'
puma (3.5.2) lib/puma/server.rb:406:in `process_client'
puma (3.5.2) lib/puma/server.rb:271:in `block in run'
puma (3.5.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
  Rendering /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (0.6ms)
  Rendered collection of /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/routes/_route.html.erb [69 times] (10.5ms)
  Rendered /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/routes/_table.html.erb (3.0ms)
  Rendering /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (5.2ms)
  Rendered /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (34.3ms)
Started POST "/" for 192.168.1.254 at 2017-08-04 09:23:50 +0800
ActionController::RoutingError (No route matches [POST] "/"):

--------------------------------------
genieacs server web page access ok by: http://192.168.1.11:3000/
but the device(ip=192.168.1.254 with tr069 enabled) not found!

**Comment by zaidka** [comment]
You have the wrong project. This is only for GenieACS core related issues. And if you're not sure what you're facing is a bug, please use the mailing list instead.
