### ISSUE TITLE
 genieacs-nbi auth problem

### ISSUE THREAD

**Issue by zoto13** [zaidka/genieacs#257]
We are trying to connect our CPE with genieacs. The device is successfully discovered, even periodic inform post form CPE is OK. But the problem is, when we try to modify a parameter from either genieacs GUI or API, we get an error below,

==> genieacs-nbi-err.log <==
2017-09-17T17:59:32.494Z [ERROR] Uncaught exception; exceptionName="TypeError" exceptionMessage="Data must be a string or a buffer" exceptionStack="TypeError: Data must be a string or a buffer\n    at Hash.update (crypto.js:97:16)\n    at Object.exports.digest (/root/genieacs/lib/auth.js:53:36)\n    at ClientRequest.<anonymous> (/root/genieacs/lib/api-functions.js:102:33)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at ClientRequest.emit (events.js:210:7)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)\n    at Socket.socketOnData (_http_client.js:454:20)\n    at emitOne (events.js:115:13)"
2017-09-17T18:00:02.507Z [ERROR] Worker died; pid=16484 exitCode=1
2017-09-17T18:00:03.083Z [INFO] Worker listening; pid=16602 address="0.0.0.0" port=7557

The configuration auth.js is modified as described in wiki guide as below, genieacs-nbi session was also restarted,

[root@test-wan config]# cat auth.js 
"use strict";

function connectionRequest(deviceId, url, username, password, callback) {
  return callback("itms","itms");
}

exports.connectionRequest = connectionRequest;
[root@test-wan config]#

From wirshark, it seems HTTP Post from genieacs was sending connection request without auth info, no more messge exchange after that until CPE origenates another inform.

GET / HTTP/1.1
Host: 192.168.10.25:7547
Connection: keep-alive

HTTP/1.1 401 Authorization Required
Content-Length: 0
Server: TR069 client TCP connection request Server
WWW-Authenticate: Digest realm="", qop="auth", nonce="6kffGyVCsGzDtJUml27yvhxQ2EBKP8o", algorithm="MD5", domain="/"
Connection: close

**Comment by zoto13** [comment]
well, not familiar with js, after some digging, cause of this crash is found.
This cpe sent an empty string as realm, thus auth.js was failed to parse the realm value in authHeader. So the response msg was never sent from acs side. 
Hard code realm='' in auth.js as workaround for now...

**Comment by zaidka** [comment]
I took a quick look at the spec and I'm under the impression that a blank string is a legal value for realm. This patch should fix the error.
