### ISSUE TITLE
MongoError: Mod on _id not allowed

### ISSUE THREAD

**Issue by casdr** [zaidka/genieacs#262]
Since I did an upgrade to 1.1.1, cwmp crashes on with the following error when an FRITZ!Box does an inform:

```
2017-10-04T06:00:32.848Z [ERROR] Uncaught exception; pid=31981 exceptionName="MongoError" exceptionMessage="Mod on _id not allowed" exceptionStack="MongoError: Mod on _id not allowed\n    at Function.MongoError.create (/opt/genieacs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)\n    at toError (/opt/genieacs/node_modules/mongodb/lib/utils.js:139:22)\n    at /opt/genieacs/node_modules/mongodb/lib/collection.js:1059:60\n    at getLastErrorCallback (/opt/genieacs/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:466:18)\n    at /opt/genieacs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:469:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"
```

**Comment by zaidka** [comment]
I'm guessing you're using an older version of MongoDB. Try upgrading to at least 2.6.

**Comment by casdr** [comment]
That fixed it, thanks!
