### ISSUE TITLE
Uncaught exception in lib/cache.js - Lock Expired

### ISSUE THREAD

**Issue by bpbp-boop** [zaidka/genieacs#268]
Hello, since upgrading to git master from v1.0 I am seeing this following:

```
[ERROR] Uncaught exception; pid=9903 exceptionName="Error" exceptionMessage="Lock expired" exceptionStack="Error: Lock expired
    at Command.callback (/usr/src/app/lib/cache.js:127:24)
    at normal_reply (/usr/src/app/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/usr/src/app/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.returnReply (/usr/src/app/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/usr/src/app/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:274:27)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)"
[ERROR] Worker died; pid=9903 exitCode=7
```

Disabling redis and moving to the MongoDB for caching produces the following (although not as much):

```
[ERROR] Uncaught exception; pid=38 exceptionName="Error" exceptionMessage="Lock expired" exceptionStack="Error: Lock expired
    at /usr/src/app/lib/cache.js:223:24
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:120:56)
    at /usr/src/app/node_modules/mongodb/lib/collection.js:1252:5
    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)"
```

**Comment by zaidka** [comment]
I suspect this has something to do with the server being under heavy load. Can you confirm?

**Comment by bpbp-boop** [comment]
It's possible - we're currently managing a few thousand devices with hourly informs and we are generating a preset per device for provisioning (as we started using GenieACS before the provisioning feature existed :) ). 

Load average hovers around 1 and disk IO seems to be under control though.

**Comment by zaidka** [comment]
Hourly inform shouldn't be a problem unless a large number of devices inform at the exact same time. Can you look at the logs at around the time of the exception to see roughly how many devices connected?

What version of MongoDB are you using?

**Comment by bpbp-boop** [comment]
Mongo is 3.4.9. It does seem to coincide with busier periods, maybe a 10-15 informing at a similar time.
