### ISSUE TITLE
setParameter value support hexBinary

### ISSUE THREAD

**Issue by zoto13** [zaidka/genieacs#274]
error log:
2017-11-28T17:46:50.838Z [ERROR] Uncaught exception; exceptionName="Error" exceptionMessage="Parameter value type \"xsd:hexBinary\" not recognized." exceptionStack="Error: Parameter value type \"xsd:hexBinary\" not recognized.\n    at Object.sanitizeParameterValue (/root/genieacs/lib/device.js:62:17)\n    at /root/genieacs/lib/session.js:1220:14\n    at Map.forEach (native)\n    at generateSetRpcRequest (/root/genieacs/lib/session.js:1209:17)\n    at rpcRequest (/root/genieacs/lib/session.js:970:37)\n    at /root/genieacs/lib/session.js:811:14\n    at clear (/root/genieacs/lib/session.js:1596:12)\n    at rpcRequest (/root/genieacs/lib/session.js:806:12)\n    at /root/genieacs/lib/session.js:735:18\n    at /root/genieacs/lib/session.js:122:12"

workaroud:
check hexBinary value as string,
vim /usr/lib/node_modules/genieacs/lib/device.js

      case 'xsd:hexBinary':
        if (typeof parameterValue[0] !== 'string') {
          parameterValue[0] = '' + parameterValue[0];
        }
        break;

**Comment by zaidka** [comment]
That's not a standard type. Perhaps reach out to the device manufacturer to have them fix this instead.
