### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by rocmehra** [zaidka/genieacs#56]
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/0.10.25/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)
18 Dec 18:34:26 - Worker 7837 died (8)

**Comment by sinkcup** [comment]
I have the same error, someone has an idea?

##run:
`
sudo apt-get install npm nodejs-legacy redis-server mongodb-server
sudo npm install -g genieacs
genieacs-cwmp
`

##result:
`
/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/0.10.25/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)
5 Jan 14:04:37 - Worker 32312 died (8)
`

**Comment by zaidka** [comment]
Was the installation of genieacs and its libxmljs dependency successful? Did you see any error messages?

**Comment by sinkcup** [comment]
libxmljs is ok, only `genieacs-cwmp` return error.

run `genieacs-nbi` is ok, result:

    5 Jan 14:22:40 - Worker 32736 listening to 0.0.0.0:7557
    5 Jan 14:22:40 - Worker 32737 listening to 0.0.0.0:7557

run `genieacs-fs` is ok, result:
    5 Jan 14:30:06 - Worker 668 listening to 0.0.0.0:7567
    5 Jan 14:30:06 - Worker 669 listening to 0.0.0.0:7567

**Comment by zaidka** [comment]
Try installing genieacs from source and revert to v0.11.0 of libxmljs as I suggested in a previous comment.

**Comment by sinkcup** [comment]
ok. thanks. It's very unbelievable.

    git clone https://github.com/zaidka/genieacs.git
    cd genieacs
    npm install
    npm run configure
    npm run compile

    sudo npm install libxmljs@0.11.0

    make: Leaving directory '/home/ubuntu/code/genieacs/node_modules/libxmljs/build'
    libxmljs@0.11.0 node_modules/libxmljs
    ├── bindings@1.1.1
    └── nan@1.1.2

    npm install libxmljs@0.11.0

    make: Leaving directory '/home/ubuntu/code/genieacs/node_modules/libxmljs/build'
    libxmljs@0.11.0 node_modules/libxmljs
    ├── bindings@1.1.1
    └── nan@1.1.2

    ./bin/genieacs-cwmp 

    5 Jan 15:19:42 - Worker 9151 listening to 0.0.0.0:7547
    5 Jan 15:19:42 - Worker 9154 listening to 0.0.0.0:7547

**Comment by sinkcup** [comment]
now (cause error):

    "dependencies": {
    "libxmljs": "~0.11.0",

suggest:
    "dependencies": {
    "libxmljs": "0.11.0",

**Comment by Li4uk** [comment]
Thank`s. I`m set dependencies and rebuild app. Work fine!)))
"dependencies": {
"libxmljs": "0.11.0",

**Comment by BoubakrEchieb** [comment]
i have the same problem  ... i follow this but still have errors :(

**Comment by BoubakrEchieb** [comment]
~$ genieacs-cw
the result :
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/5.8.0/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:413:34)
1 Apr 14:34:21 - Worker 16775 died (1)
/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 → /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/5.8.0/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:413:34)
1 Apr 14:34:21 - Worker 16776 died (1)
/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
  ^

**Comment by lengyao88** [comment]
Last login: Fri Mar 24 14:52:20 on ttys002
clydeiMac:~ cly$ stf doctor
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/6.10.1/darwin/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by DrumSergio** [comment]
Hi @lengyao88 !

Please, use [the mailing list](http://lists.genieacs.com). And please, post your operating system (Is it a Mac? I think it is not supported there...) along with which versions of GenieACS, node.js, mongo you are using.

Thank you!

**Comment by Sylar89** [comment]
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/7.8.0/darwin/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
